In [ ]:
import numpy as np


In [ ]:
np.

In [7]:
np.array2string?

In [9]:
np.atleast_3d?

In [13]:
np.convolve?

In [14]:
np.compress?

In [16]:
np.cumproduct((1,2,3))

array([1, 2, 6], dtype=int32)

In [17]:
np.digitize?

In [19]:
np.ediff1d?

In [20]:
np.einsum?

In [26]:
np.flatiter?

In [27]:
np.flatnonzero?

In [30]:
np.fmax?

In [31]:
np.format_float_scientific?

In [32]:
np.format_float_positional?

In [34]:
np.fromfunction?

In [36]:
np.full?

In [113]:
np.fv?
np.pv?
np.ipmt?
np.irr?
np.mirr?
np.nper?
np.npv?
np.pmt?
np.ppmt?

In [39]:
np.gcd?
np.lcm?

In [42]:
np.geomspace?
np.logspace
np.linspace

In [44]:
np.gradient?


In [49]:
np.histogram?
np.histogram2
np.histogram_bin_edges
np.histogramdd


In [57]:
np.i0?

In [62]:
np.iinfo(int),np.iinfo(np.int64)

(iinfo(min=-2147483648, max=2147483647, dtype=int32),
 iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64))

In [63]:
np.isin

In [66]:
np.info?

In [69]:
np.inner?

In [70]:
np.interp?

In [71]:
np.intersect1d?

In [75]:
np.isneginf
np.isposinf


In [ ]:
np.ix_?

In [80]:
np.lexsort?

In [83]:
np.linalg?

In [87]:
np.ma?

In [89]:
np.meshgrid?

In [90]:
np.mgrid?

In [92]:
np.moveaxis?

In [93]:
np.nanargmax
np.nanargmin
np.nancumprod
np.nancumsum
...


In [94]:
np.nanpercentile
np.nanquantile


<function numpy.core.fromnumeric.ndim(a)>

In [95]:
np.ndim?

In [97]:
np.nested_iters?

In [99]:
np.newaxis


In [102]:
np.ogrid?

In [103]:
np.outer?

In [110]:
np.pad
np.partition
np.piecewise?
np.place?
np.poly?

In [111]:
np.poly...



SyntaxError: invalid syntax (<ipython-input-111-39779e405f90>, line 1)

In [112]:
np.ptp?

In [115]:
np.where

<function numpy.core.multiarray.where>

In [116]:
np.vander?

In [117]:
np.unique
np.union1d
np.unwrap?

In [ ]:
np.r...


In [118]:
np.searchsorted
np.select


In [4]:
np.save?

In [3]:
np.savez?

In [5]:
np.searchsorted?

In [9]:
np.swapaxes?

In [11]:
np.take?

In [13]:
np.tensordot?

In [14]:
np.tile?

In [15]:
np.trace?

In [16]:
np.trapz?

In [17]:
np.tri?

In [19]:
np.trim_zeros?

In [28]:
np.linalg?

In [29]:
import scipy as sci



In [34]:
import numexpr

In [36]:
import mkl
import mkl_random
import mkl_fft
import glob2


In [50]:
import glob
variable = ('')
glob.glob

In [59]:
import pandas as pd

In [95]:
pd.wide_to_long
pd.concat
pd.crosstab
pd.cut
pd.date_range?
pd.datetime
pd.factorize?
pd.get_dummies
pd.get_option?
pd.groupby?
pd.infer_freq
pd.interval_range
pd.lreshape?
pd.match?
pd.melt?
pd.merge
pd.merge_asof
pd.merge_ordered?
pd.notna
pd.notnull?
pd.period_range
pd.pivot
pd.pivot_table
pd.qcut?
pd.set_option?
pd.timedelta_range
pd.to_datetime
pd.unique
pd.value_counts
pd.wide_to_long

In [97]:
from PIL import Image
import PIL

In [106]:
PIL.Image.composite
PIL.Image.effect_mandelbrot?

In [107]:
import matplotlib.pyplot as plt
%matplotlib inline

In [138]:
img = PIL.Image.effect_mandelbrot((1000,1000),(-0.5,0.5,0,1),250)

In [165]:
img = np.array(img)

    PIL

In [147]:
import skimage

In [167]:
viewer = skimage.viewer.ImageViewer(img)

In [169]:
import numexpr

In [172]:
numexpr.evaluate?

In [183]:
%timeit numexpr.evaluate('a+b')

122 ms ± 2.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [185]:
%time _ = numexpr.evaluate('a+b')

Wall time: 109 ms


In [212]:
a = np.random.randint(0,255,(80000,6000,3))

b = np.random.randint(0,255,(80000,6000,3))

In [213]:
%time _ = a**2 + 3*b

Wall time: 1min 51s


In [214]:
%time _ = numexpr.evaluate('a**2 + 3*b')

Wall time: 22.8 s


In [238]:
(60 + 51) / 22.8

4.868421052631579

In [ ]:
%time _ = numexpr.evaluate

In [203]:
_.shape

(8000, 6000, 3)

In [182]:
%timeit a+b

248 ms ± 4.09 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [186]:
%time _ = a+b

Wall time: 261 ms


In [188]:
numexpr.detect_number_of_cores()

12

In [189]:
numexpr.detect_number_of_threads()

8

In [194]:
numexpr.MAX_THREADS

64

In [195]:
numexpr.nthreads

8

In [196]:
numexpr.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/TAG_server/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/TAG_server/Anaconda3\\Library\\include']


In [229]:
from numba import jit
jit?


In [221]:

def add(a,b):
    return a +b

In [222]:
%time add(a,b)

Wall time: 38 s


array([[[420, 108, 207],
        [264, 242, 466],
        [266, 320, 367],
        ...,
        [209, 404, 332],
        [ 73, 409, 184],
        [175, 169,  70]],

       [[218, 446, 379],
        [152, 276, 118],
        [ 95, 202, 175],
        ...,
        [190, 305, 288],
        [156, 285, 417],
        [419, 182, 364]],

       [[396, 264, 145],
        [125,  11, 295],
        [102, 363, 251],
        ...,
        [281, 259, 258],
        [276, 366, 445],
        [270, 117, 226]],

       ...,

       [[219, 215, 207],
        [152, 244,  10],
        [206, 330, 265],
        ...,
        [458, 136, 343],
        [103, 371, 165],
        [365,  85, 414]],

       [[383, 340, 348],
        [456, 409, 325],
        [167, 135, 291],
        ...,
        [231, 269, 252],
        [431, 245, 364],
        [390, 178, 282]],

       [[306, 235, 218],
        [253, 289, 274],
        [270, 272, 130],
        ...,
        [237,  36, 342],
        [311, 478, 253],
        [191, 226, 347]]

In [225]:
@jit
def add(a,b):
    return a +b

In [226]:
%time _ = add(a, b)

Wall time: 55.1 s


array([[[420, 108, 207],
        [264, 242, 466],
        [266, 320, 367],
        ...,
        [209, 404, 332],
        [ 73, 409, 184],
        [175, 169,  70]],

       [[218, 446, 379],
        [152, 276, 118],
        [ 95, 202, 175],
        ...,
        [190, 305, 288],
        [156, 285, 417],
        [419, 182, 364]],

       [[396, 264, 145],
        [125,  11, 295],
        [102, 363, 251],
        ...,
        [281, 259, 258],
        [276, 366, 445],
        [270, 117, 226]],

       ...,

       [[219, 215, 207],
        [152, 244,  10],
        [206, 330, 265],
        ...,
        [458, 136, 343],
        [103, 371, 165],
        [365,  85, 414]],

       [[383, 340, 348],
        [456, 409, 325],
        [167, 135, 291],
        ...,
        [231, 269, 252],
        [431, 245, 364],
        [390, 178, 282]],

       [[306, 235, 218],
        [253, 289, 274],
        [270, 272, 130],
        ...,
        [237,  36, 342],
        [311, 478, 253],
        [191, 226, 347]]

In [227]:
%time _ = add(a ,b)

Wall time: 49.1 s


In [231]:
@jit(target='cpu')
def add(a, b):
    return a + b

In [232]:
%time _ = add(a, b)

Wall time: 49 s


In [233]:
%time _ = add(a, b)

Wall time: 1min 11s


In [239]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [257]:
''.join([this.d.get(i,' ') for i in this.s])


'The Zen of Python  by Tim Peters  Beautiful is better than ugly  Explicit is better than implicit  Simple is better than complex  Complex is better than complicated  Flat is better than nested  Sparse is better than dense  Readability counts  Special cases aren t special enough to break the rules  Although practicality beats purity  Errors should never pass silently  Unless explicitly silenced  In the face of ambiguity  refuse the temptation to guess  There should be one   and preferably only one   obvious way to do it  Although that way may not be obvious at first unless you re Dutch  Now is better than never  Although never is often better than  right  now  If the implementation is hard to explain  it s a bad idea  If the implementation is easy to explain  it may be a good idea  Namespaces are one honking great idea    let s do more of those '

In [255]:
this.s

"Gur Mra bs Clguba, ol Gvz Crgref\n\nOrnhgvshy vf orggre guna htyl.\nRkcyvpvg vf orggre guna vzcyvpvg.\nFvzcyr vf orggre guna pbzcyrk.\nPbzcyrk vf orggre guna pbzcyvpngrq.\nSyng vf orggre guna arfgrq.\nFcnefr vf orggre guna qrafr.\nErnqnovyvgl pbhagf.\nFcrpvny pnfrf nera'g fcrpvny rabhtu gb oernx gur ehyrf.\nNygubhtu cenpgvpnyvgl orngf chevgl.\nReebef fubhyq arire cnff fvyragyl.\nHayrff rkcyvpvgyl fvyraprq.\nVa gur snpr bs nzovthvgl, ershfr gur grzcgngvba gb thrff.\nGurer fubhyq or bar-- naq cersrenoyl bayl bar --boivbhf jnl gb qb vg.\nNygubhtu gung jnl znl abg or boivbhf ng svefg hayrff lbh'er Qhgpu.\nAbj vf orggre guna arire.\nNygubhtu arire vf bsgra orggre guna *evtug* abj.\nVs gur vzcyrzragngvba vf uneq gb rkcynva, vg'f n onq vqrn.\nVs gur vzcyrzragngvba vf rnfl gb rkcynva, vg znl or n tbbq vqrn.\nAnzrfcnprf ner bar ubaxvat terng vqrn -- yrg'f qb zber bs gubfr!"

In [263]:
import mkl_random, mk
mkl_random.randint(0,100)

13

In [274]:
%timeit mkl_random.randint(0,100,(1000,1000))

1.7 ms ± 10.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [275]:
%timeit np.random.randint(0,100,(1000,1000))

6.62 ms ± 49.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%mkdir




np.testing.assert_allclose(model.predict(x), predict(x), atol=1e-5)